### PR TITLE
use boost uint32_t instead of std

### PR DESCRIPTION
**Pull request by iTrooz**
Right now the build is failing for me because it can't find `std::uint32_t`. I think it was supposed to use boost type

### CODE REVIEW

**Comment by JusticeRage** [comment]
Hi! Are you building this project independently, or as part of Manalyze with the provided CMake file?
This project can stand alone, but if used independently there are probably some build options I could provide to make sure the build works.

**Comment by iTrooz** [comment]
Hey ! Initially I built it as part of Manalyze, but I just tried compiling hash-library by itself, and it still fails with the same error:
```In file included from /home/itrooz/tmp3/hash-library/sha512.cpp:2:
/home/itrooz/tmp3/hash-library/sha512.h:19:52: error: ‘std::uint32_t’ has not been declared
   19 | void sha_process(sha512_state& md, const void* in, std::uint32_t inlen);
      |                                                    ^~~
make[2]: *** [CMakeFiles/hash-library.dir/build.make:174: CMakeFiles/hash-library.dir/sha512.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....```

**Comment by JusticeRage** [comment]
Just to clarify, the build works fine in the context of a global build with Manalyze?
Some compiler options are only set in the top-level `CMakeFiles.txt`, which is why I'm asking.

**Comment by iTrooz** [comment]
Nope, both https://github.com/JusticeRage/Manalyze and https://github.com/JusticeRage/hash-library fail with the error I gave above, when trying to build (to build, I am using `rm -rf build && cmake -B build && cmake --build build -j 4`)

I am using Arch Linux with gcc 13.2.1, if that helps

**Comment by JusticeRage** [comment]
How about changing "#include <boost/cstdint.hpp>" to `#include <cstdint>` on [this line](#include <boost/cstdint.hpp>), and replacing the references to `boost::uint64_t ` by `std::uint64_t `?
Does that fix the issue? I think this would be cleaner, probably. Otherwise I'll merge your PR!

**Comment by iTrooz** [comment]
It would work, but you seem to already use boost types everywhere else in your codebase (e.g. https://github.com/JusticeRage/hash-library/blob/3b7d7af23f5ea4785a78f7f8e9c70b08e98f122f/hashes.h#L62), so it seems weird to use std types just for this case

Are you sure you want me to use std types here ?

**Comment by JusticeRage** [comment]
Ah, yes, you're correct. It would be best to switch to `std::` types everywhere but for now I'll just merge. Thanks for your fix and the discussion!

**Pull request merged**
